### PR TITLE
Heatmap of Smashing Magazine Project

### PR DESCRIPTION
**Pull request by AdesojiCodeMaster**
Teardown project of Smashing Magazine:
Page to teardown : [https://www.smashingmagazine.com/]

-Live Demo [https://rawcdn.githack.com/AdesojiCodeMaster/TEARDOWN-CLONE/d98fd82de4e7108ed3db543ee43c681e4b71965e/index.html]

### CODE REVIEW

**Comment by AdesojiCodeMaster** [comment]
Teardown project of Smashing Magazine:
 [Page to teardown](https://www.smashingmagazine.com/) 

 [-Live Demo](https://rawcdn.githack.com/AdesojiCodeMaster/TEARDOWN-CLONE/9286d31ac5ec16b64319b173c27c254b8f3b4558/index.html)

**Comment by peterrobert** [comment]
### PULL REQUEST UNDER REVIEW BY PETER ROBERT (TSE)

**Comment by AdesojiCodeMaster** [comment]
- Teardown project: By  **Adesoji Adewumi** and  **Carlos Robles**.

- Project Title: HeatMap of Smashing Magazine.

-  [Page Worked on](https://www.smashingmagazine.com/)

- [Live Demo](https://rawcdn.githack.com/AdesojiCodeMaster/TEARDOWN-CLONE/cdbc595a85da3fa6f90d394944d003a8cd4c8dec/index.html)

**Comment by peterrobert** [comment]
### PULL REQUEST UNDER REVIEW BY PETER ROBERT

**Comment by carlos-ssh** [comment]
Thanks for your support. :D

**Comment by AdesojiCodeMaster** [comment]
Thanks for your supports. We really appreciate.

**Comment by AdesojiCodeMaster** [comment]
Thanks for your supports. We really appreciate it!

**Pull request merged**
